# Generated by Django 2.1.7 on 2019-08-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('Table_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('id', models.IntegerField()),
                ('id_str', models.IntegerField()),
                ('text', models.TextField()),
                ('truncated', models.BooleanField()),
                ('in_reply_to_status_id', models.IntegerField(null=True)),
                ('in_reply_to_status_id_str', models.IntegerField(null=True)),
                ('in_reply_to_user_id', models.IntegerField(null=True)),
                ('in_reply_to_screen_name', models.IntegerField()),
                ('user', models.TextField()),
            ],
        ),
    ]
